### ISSUE TITLE
Update to react-router 4

### ISSUE THREAD

**Issue by antoniocapelo** [moxystudio/react-with-moxy#1] opened 2017-11-13 10:00 UTC
_From @satazor on March 16, 2017 2:43_

If we do upgrade, do not forget to remove 'preprocess-loader' from webpack config.

_Copied from original issue: moxystudio/react-with-moxy#40_

**Comment by satazor** [comment] 2017-11-23 19:45
react-router 4 has a lot of problems and I would say it's broken by design because it doesn't play well with pure components. Therefore, I'm closing this issue and will open a new one to explore other routing solutions.

**Closed as completed by satazor** 2017-11-23 19:45 UTC
Labels: enhancement
